# Generated by Django 5.2.1 on 2025-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Адміністратор"), ("client", "Клієнт")],
                default="client",
                max_length=10,
            ),
        ),
    ]
