# Generated by Django 5.2.1 on 2025-05-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Тривалість у днях"),
                ),
                (
                    "access_time",
                    models.CharField(help_text="Наприклад, 7:00–16:00", max_length=50),
                ),
                (
                    "freeze_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Кількість днів заморозки"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("morning", "Ранкова"),
                            ("daytime", "Денна"),
                            ("unlimited", "Безлімітна"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
